### ISSUE TITLE
Unable to connect to monitor stream through Websocket

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#147]
Loop REST v0.4.0-beta.

When trying to connect through WebSocket, we are getting "Unexpected response code 200" error:
![image (1)](https://user-images.githubusercontent.com/23240721/73865021-9aae1d00-4810-11ea-8895-5ca37aafb6f0.png)

**Comment by guggero** [comment]
That endpoint is currently not a websocket endpoint, just a normal HTTP GET that returns a new line of JSON on every update. That format is a bit hard to use, that's why we added the `ListSwaps` command. That serves from memory and can be polled regularly.

We probably do want to use websockets for streaming calls in loop and lnd but we'd need to evaluate which library to use for that and if it would interfere with the existing REST proxy.

**Comment by ShahanaFarooqui** [comment]
@guggero 
I tried to search for the documentation for monitor REST but i was unable to find anywhere. So, I thoguht to try GET & Websocket both, to monitor the loop. Is there any documentation on the monitor GET which i missed?

If we can get the data through GET then we will not need websocket anymore.

**Comment by guggero** [comment]
The updated REST API documentation is here: https://lightning.engineering/loopapi/
There's [`ListSwaps`](https://lightning.engineering/loopapi/#listswaps) for all swaps and [`SwapInfo`](https://lightning.engineering/loopapi/#swapinfo) for one specific swap.

**Comment by halseth** [comment]
Looks like this got resolved? Closing.
