### ISSUE TITLE
Swap REST id with forward slashes returns 'Not Found'

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#154]
Loop v0.4.1
API: /v1/loop/swap/<hash>
Sample hashed id: SAUZul5aQB9xyyH5omWs5bxSsmUubL+MCA4XK2//pV4=
Sample encoded GET request: http://localhost:8081/v1/loop/swap/SAUZul5aQB9xyyH5omWs5bxSsmUubL+MCA4XK2%2F%2FpV4=

We are unable to get the swap response when the id has '/' in the value even after encoding the slash with '%2F'.

**Comment by guggero** [comment]
All special characters need to be encoded. Most likely the `+` symbol is what breaks it (because that is interpreted as a space in URL format). It's easiest to use the `encodeURIComponent()` function of the browser to get the correctly encoded swap ID.
I'll update the documentation to mention this.

**Comment by ShahanaFarooqui** [comment]
I was testing it through postman and forgot to manually encode +. But this time i encoded all special character, still the same error..

id_bytes from swaps API : SAUZul5aQB9xyyH5omWs5bxSsmUubL+MCA4XK2//pV4=
encoded ID: SAUZul5aQB9xyyH5omWs5bxSsmUubL%2BMCA4XK2%2F%2FpV4%3D
Request API: http://localhost:8081/v1/loop/swap/SAUZul5aQB9xyyH5omWs5bxSsmUubL%2BMCA4XK2%2F%2FpV4%3D

**Comment by guggero** [comment]
My apologies, what I wrote does indeed not work. We did test this but in our tests we apparently never had a `/` in the ID.
The `grpc-gateway` library that we use can't handle the `%2f` encoded slash correctly. Luckily it also supports the URL safe base64 encoding scheme that uses `-` instead of `+` and `_` instead of `/`.

You should be able to use `data.replace(/_/g, '/').replace(/-/g, '+')` instead of `encodeURIComponent()`.
The URL http://localhost:8081/v1/loop/swap/SAUZul5aQB9xyyH5omWs5bxSsmUubL-MCA4XK2__pV4= should work.

**Comment by ShahanaFarooqui** [comment]
Yeah, this solution works as expected. Thanks.
