### ISSUE TITLE
Receiving 2x swap fee values from REST quote than GRPC

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#159]
Loop v0.4.1

REST API quote is returning 2x max swap fee than GRPC:

GRPC (loop out amount):
`250000 => Max swap fee = 175 & 2000000 => Max swap fee = 1050`

REST (http://localhost:8081/v1/loop/out/quote/amount?conf_target=6):
`250000 => swap_fee = 350 & 2000000 => swap_fee = 2100`

**Comment by guggero** [comment]
The difference is the speed of the swap (optimization for batching).
For the CLI the default is a slow swap (the publication deadline is set 30 minutes in the future).
For gRPC and REST you have to set the `swap_publication_deadline` parameter manually. If it is not set, the default value of 0 will be used which is interpreted as "publish immediately".
Because waiting longer increases the chance of batching multiple swaps together, we give out a discount, which is the difference you see in the swap fee.

You should see exactly the same fees if you either compare CLI with the `--fast` flag and REST with `&swap_publication_deadline=0` or no flag in CLI and `&swap_publication_deadline=<unix timestamp for now + 30 minutes>` in REST.
