### ISSUE TITLE
units for on-chain fees off by a factor of 100

### ISSUE THREAD

**Issue by AndySchroder** [lightninglabs/loop#176]
If I run `loop quote out` it says the `miner_fee` is `2440`. If I run `loop out` and choose `x` to expand fee detail, the `Max on-chain fee` is `244000`. What are the units for each of these fees, and why are they different? The other fees all match up between the two commands.

**Comment by guggero** [comment]
Because there is always one side of a swap touching the chain, all units are in satoshis.
The difference between the two values is the multiplier that changed in https://github.com/lightninglabs/loop/pull/168.
The `miner_fee` is an estimation of how much an HTLC sweep would cost _at the time of the quote_. But because fees can rise between the time a swap is initiated and the time the HTLC appears on chain, we need to allow for more chain fees than that initial estimate. Otherwise your loop would be stuck until fees come down.
That `factor` was increased from `3` to `100` to fix the issue if fees rise very quickly (as happened recently).

I'm going to document this a bit better with an upcoming PR.
