### ISSUE TITLE
Loop out fails due to poorly connected loop server

### ISSUE THREAD

**Issue by krtk6160** [lightninglabs/loop#273]
When I perform a `loop quote out`, I receive this - 
```
{
    "swap_fee_sat": "2000",
    "prepay_amt_sat": "1337",
    "htlc_sweep_fee_sat": "19085",
    "swap_payment_dest": "03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a",
    "cltv_delta": 0
}
```
The swap payment destination here is [this node](https://1ml.com/node/03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a). It has only one channel, which is with the supposedly 'main' [loop server.](https://1ml.com/node/021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d)

All my loop outs on a particular channel are failing with `2020-08-17T11:45:22Z LOOP_OUT FAILED (FAILURE_REASON_OFFCHAIN) 0.059 BTC`.
When I do a `lncli queryroutes` to the swap payment destination returned above, I receive a no routes found error. I'm guessing this is why the loop outs are failing.

However, if I do queryroutes to the 'main' [loop server](https://1ml.com/node/021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d), there is indeed a route.

How can I fix this problem? Why is a poorly connected node being assigned as the swap payment dest? Why not the main loop server?

**Comment by carlaKC** [comment]
You don't need to worry about the destination node's liquidity management. It has private channels which are not present when you query for routes to it directly, but hop hints which allow your payment to use those private channels will be provided in the invoice when you initiate a loop out. 

> However, if I do queryroutes to the 'main' loop server, there is indeed a route.

Loop out swaps need to create a hodl invoice which has a very long timeout. Your swap is likely failing because you cannot find a route which allows for the long timeout.
