### ISSUE TITLE
loopd not creating tls certificate

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/loop#364]
We are running loopd in the default location ~/go/bin

But when we run it's not creating the tls certificate and we get this error when trying to run any loop command:

`[loop] open ~/.loop/mainnet/tls.cert: no such file or directory`

We are also running `litd` in parallel if that might cause any conflicts.

**Comment by guggero** [comment]
You cannot run LiT and `loops` in parallel if LiT doesn't use the `--loop-mode=remote` or one of them uses a different data directory. What happens here is that `litd` also spun up an internal Loop daemon that's now using the exclusive lock on the `loop.db`. That's why the second `loopd` instance just hangs there and doesn't continue. See https://github.com/lightninglabs/pool/issues/177 where a similar issue with Pool is reported.
I'm putting this on my list of things to fix soon.

**Comment by guggero** [comment]
We added a timeout to the exclusive lock on the `loop.db`. So this shouldn't happen anymore that one instance of Loop is silently not starting up. If you're now experiencing problems with running LiT, we suggest you use the `--loop-mode=remote` to point LiT to the existing Loop instance instead of starting its own.
