### ISSUE TITLE
Bumping miner fee or change lnd's fee estimate for initiated loop (pending htlcs)

### ISSUE THREAD

**Issue by xjmzx** [lightninglabs/loop#417]
Not on Slack and rely on Telegram groups for gaps in knowledge, so please go easy if this is unwarranted.

I have a pending htlcs.` lncli listchannnels`

"hash_lock": "c2529ae00122fca5a04ab855f83a5751dd321e29c8dc041525360ba7adf0b167"

"pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "8227432",
                    "hash_lock": "c2529ae00122fca5a04ab855f83a5751dd321e29c8dc041525360ba7adf0b167",
                    "expiration_height": 698994,
                    "htlc_index": "56",
                    "forwarding_channel": "0",
                    "forwarding_htlc_index": "0"

lnd log shows:

LOOP: c2529a Required fee 0.00001353 BTC exceeds max miner fee of 0.00001159 BTC
LOOP: c2529a Not revealing preimage

As I understand, the user who initiated the loop out is required to sweep, before the block height reverts the transaction as void.

"The user sweeps that output to his wallet. He can only do this by disclosing the preimage in the spending transaction."

What does this mean? How does a user achieve disclosure?

"... However, the user can leverage fee bumping tools such as RBF and CPFP to ensure a timely confirmation."

Reference: https://blog.lightning.engineering/technical/posts/2019/04/15/loop-out-in-depth.html

I guess this is fairly new territory with recent lnd updates, so wanted to suggest there may be a need for clarification in the docs.

Related

Reference: https://github.com/lightninglabs/lightning-terminal/issues/239
Reference: https://github.com/lightninglabs/loop/issues/354

**Comment by carlaKC** [comment]
So once you've initiated a loop out swap the following happens: 
* Your client creates an off-chain payment to the server
* The server doesn't know the preimage for this payment, so can't claim the funds
* The server publishes a htlc on chain with the same payment hash

If your client decides to claim the htlc on chain, then the server finds out the preimage (we see it in your claim tx) and will pull the off-chain amount. This is how the swap is trustless, we can only pull off-chain if you first pull on-chain. 

We have a safeguard "max miner" fee in the client so that you don't claim on-chain if fees are going to be too high (possible if there's a big fee spike right after you create the swap). 

> LOOP: c2529a Required fee 0.00001353 BTC exceeds max miner fee of 0.00001159 BTC

So what's happening here is that your client has decided it's too expensive to sweep, so it's just going to let the swap fail.

**Comment by carlaKC** [comment]
What bitcoin backend are you using for fee estimation?

**Comment by xjmzx** [comment]
"What bitcoin backend are you using for fee estimation?"  

lnd

This was my first swap using LIT and I just ran loop without checking on fee estimation configs. I'll read up on it.

"We have a safeguard "max miner" fee in the client so that you don't claim on-chain if fees are going to be too high"

As you said, the htcl timed out in the end. Good to know, I understand what's going on now.
I guess that fee bumping is automatically bound to the range of max-miner fees?

Thanks for explaining. Sorry if it was unnecessary to make an issue, please close it.

I'll get on Slack if that's for both users and developers.

**Comment by carlaKC** [comment]
> I guess that fee bumping is automatically bound to the range of max-miner fees?

Yes, that's the case. 

> Thanks for explaining. Sorry if it was unnecessary to make an issue.

Always happy to help out! Issues are welcome because somebody else with the same problem can now read through this and hopefully answer their own questions :)

**Comment by carlaKC** [comment]
Out of curiosity, what version of loop are you running? Upgrading could help the max miner fee estimation.

**Comment by ibz** [comment]
So if the client decides to not claim the on-chain funds (due to miner fee being too high) - the only option at this point is to let the HTLC time out and then the off-chain funds will return to the client? Is that correct?

**Comment by ibz** [comment]
I did not manage to find a way to change the "max miner fee" setting, so what did was the following (writing it here in case anyone else has this issue and needs a quick workaround):

I changed `feeurl` in lnd's config file to point to fake file which contained some intentionally very low fees. This way I tricked lnd to think the fee will be much lower and thus accept it. I know this workaround would be not realistic on a production node. I could do it on mine because it's not really used by anyone yet.

I wonder if there is a better solution.

BTW, issue #300 is also related.
