### ISSUE TITLE
Defaults to "invoices.macaroon", but lnd makes "invoice.macaroon"

### ISSUE THREAD

**Issue by wbobeirne** [lightninglabs/loop#49]
Loop looks for an invoice macaroon named `invoices.macaroon`, but LND names the file `invoice.macaroon`, no s.

**Loop**
https://github.com/lightninglabs/loop/blob/c5572349699c2128318ec0d5db40baa04aa348ef/lndclient/lnd_services.go#L178
**LND** <sup>According to docs, didn't find where in code this happens.</sup>
https://github.com/lightningnetwork/lnd/blob/c5ece1e509e8686e5d3753a2fbe1176fc615040b/macaroons/README.md#generated-macaroons

This results in the following error when using a default setup:

```
unable to obtain macaroons: open /home/wbobeirne/.lnd/data/chain/bitcoin/mainnet/invoices.macaroon: no such file or directory
```

**Comment by Roasbeef** [comment]
So that `invoice.macaroon` is the an existing macaroon that only gives you access to invoice calls. There's a newer  `invoices.macaroon` (with the "s"s), that is for the new invoice sub-server: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/invoices_server.go#L62

Is the version of `lnd` you're running with compiled with the relevant build tags?

**Comment by wbobeirne** [comment]
Ahh, had built it but hadn't started it to generate the new files. Just assumed it was a mistake due to how similar the name is. Ignore me!
