### ISSUE TITLE
Pay for inbound liquidity with on-chain funds

### ISSUE THREAD

**Issue by stridentbean** [lightninglabs/loop#80]
**Issue**
Currently, when you create a lightning wallet you have no inbound or outbound liquidity. This makes sending and receiving funds harder.

**Proposed Solution** 
Create a feature where loop receives on-chain funds and then opens a channel to that user.

**Comment by alexbosworth** [comment]
Is the goal here to arrive at a balanced channel? It's probably good to get a bit more specific because inbound liquidity is fundamentally more complex because it involves time value

One additional solution is potentially to allow channels to be funded from external outputs like an exchange withdrawal, and then Loop Out from there to achieve balance

**Comment by joostjager** [comment]
If I understand it correctly, this request is for a channel buying service. This isn't inside the scope of loop. Closing for now, let me know if misunderstood.
